### ISSUE TITLE
bug: `skip_files` is not OS-agnostic

### ISSUE THREAD

**Issue by nfelt14** [pawamoy/mkdocs-spellcheck#21]
### Description of the bug

The `skip_files` option accepts literal file paths, but when the file is checked it uses OS-specific file path separators, which means each file needs to be specified twice to work on Windows/Unix operating systems.

### To Reproduce

1. Set up mkdocs with plugin on Windows operating system
2. Add a file path to the `skip_files` option using Unix-style file path separators
    ```yaml
       plugins:
         - spellcheck:
             skip_files:
               - path/with/unix/seps/file.txt
     ```
4. Run mkdocs and observe how the file is not skipped

### Expected behavior

The `skip_files` option should accept file paths using Unix-style file path separators and work on both Windows and Unix operating systems.

### Environment information

```console
$ python -m mkdocs_spellcheck.debug
- __System__: Windows-10-10.0.19045-SP0
- __Python__: cpython 3.11.8
- __Environment variables__:
- __Installed packages__:
  - `mkdocs-spellcheck` v1.0.3
```
